import styles from './AboutMe.module.css';
import Image from 'next/image';
import aboutMeImg from '../Assets/vic.jpeg';
export const AboutMe = () => {
  return (
    <div className={styles.container}>

      <Image className={styles.AboutMeImg}
        src={aboutMeImg}
        width="1700px"
        height="2400px"
      />
      <div className={styles.aboutMeText}>
        <h3 className={styles.aboutMeTitle}><b>VC BEAUTY</b></h3>
        <hr />
        <p>
          MI PASIÓN POR LOS DETALLES Y LA BÚSQUEDA DE NUEVAS TENDENCIAS DE BELLEZA ME LLEVÓ POR UN CAMINO DE CONSTANTE APRENDIZAJE.<br />¿AUTODIDACTA? SI, POR SUPUESTO. PERO TAMBIÉN ME RELACIONÉ Y COMPARTÍ CONOCIMIENTOS CON LOS MEJORES ARTISTAS INTERNACIONALES.
        </p>
        <p>
          ¡EL MAQUILLAJE ES MÁS DE LO QUE IMAGINAMOS! LO USAMOS PARA VERNOS Y SENTIRNOS MEJOR, IMPACTANDO POSITIVAMENTE EN NUESTRA AUTOESTIMA.INFLUYE TAMBIÉN EN LO QUE TRANSMITIMOS A LOS DEMÁS Y AUMENTA NUESTRA CONFIANZA PARA LOGRAR LO QUE NOS PROPONGAMOS.<br /> ES FASCINANTE NO? A VECES IMPLEMENTARLO A NUESTRA RUTINA DIARIA NO RESULTA FÁCIL. IMAGÍNATE LEVANTARTE TODOS LOS DÍAS Y ESTAR MAQUILLADA! BUENO, ¡DE ESO NOS OCUPAMOS NOSOTRAS! <br />
        </p>
        <p>
          NUESTRO EQUIPO SE CONFORMA POR PROFESIONALES ALTAMENTE CAPACITADOS Y DEBIDAMENTE CERTIFICADOS CON EXPERIENCIA COMPROBADA. <br />CADA UNO DE LOS INTEGRANTES FUE SELECCIONADO POR SU CAPACIDAD Y POR SU CALIDEZ HUMANA QUE SE VE PLASMADA EN EL TRATO Y LA ATENCIÓN QUE RECIBE NUESTRO PÚBLICO. EN OG NO SOLO BRINDAMOS UN SERVICIO DE CALIDAD, SINO UNA EXPERIENCIA.
        </p>
        <p>
          TAMBIÉN DISEÑAMOS CURSOS DE CAPACITACIÓN CON TÉCNICAS INNOVADORAS PARA SEGUIR FORMANDO CADA VEZ MÁS ARTISTAS. <br />DESDE 2019 DICTAMOS NUESTROS CURSOS EN MIAMI USA, DEMOSTRANDO QUE NUESTRA FORMA DE TRABAJO Y LA CALIDAD DE LOS RESULTADOS QUE LOGRAMOS NO TIENE FRONTERAS.
        </p>
        <p>
          TENEMOS COMO OBJETIVO POTENCIAR LA BELLEZA NATURAL DE NUESTRAS CLIENTAS Y CONFIAMOS EN QUE MENOS ES MAS.<br /> POR ESO, CUIDAMOS LOS DETALLES, EVITANDO EXCESOS, Y APOSTANDO SIEMPRE A UN RESULTADO ARMÓNICO Y NATURAL.
        </p>
        <p>
          TE INVITO A QUE LOGREMOS JUNTAS TU MEJOR VERSIÓN.
        </p>
      </div>
    </div>
  )
}

export default AboutMe